name: GitHub Actions Demo
on: [push]

jobs:
  echo_shell:
    runs-on: ubuntu-latest
    steps:
      - name: "define func"
        run: |
          echo 'view_diff()
          {
            echo $1 | bash > expected
            echo $1 | ./minishell > actual
            diff expected actual
          }' > .functions.sh

      - name: "build minishell"
        run: make

      - name: "test 1"
        run: |
          source .functions.sh
          view_diff "echo hello"

      - name: "test 2"
        run: |
          source .functions.sh
          view_diff "ls"
